export const TEST_WEATHER_RESPONSE = {
    "queryCost": 1,
    "latitude": 40.7883,
    "longitude": -74.0153,
    "resolvedAddress": "West New York, NJ, United States",
    "address": "West New York, nj",
    "timezone": "America/New_York",
    "tzoffset": -4,
    "description": "Similar temperatures continuing with no rain expected.",
    "days": [
        {
            "datetime": "2025-03-11",
            "datetimeEpoch": 1741665600,
            "tempmax": 63.9,
            "tempmin": 45,
            "temp": 54.5,
            "feelslikemax": 63.9,
            "feelslikemin": 43.9,
            "feelslike": 54.3,
            "dew": 31.5,
            "humidity": 42.5,
            "precip": 0,
            "precipprob": 0,
            "precipcover": 0,
            "preciptype": null,
            "snow": 0,
            "snowdepth": 0,
            "windgust": 19.7,
            "windspeed": 9.2,
            "winddir": 190,
            "pressure": 1008.2,
            "cloudcover": 4.3,
            "visibility": 10,
            "solarradiation": 222.5,
            "solarenergy": 19.1,
            "uvindex": 7,
            "severerisk": 10,
            "sunrise": "07:13:43",
            "sunriseEpoch": 1741691623,
            "sunset": "18:58:54",
            "sunsetEpoch": 1741733934,
            "moonphase": 0.41,
            "conditions": "Clear",
            "description": "Clear conditions throughout the day.",
            "icon": "clear-day",
            "stations": [
                "KTEB",
                "KLGA",
                "F1417",
                "KNYC"
            ],
            "source": "comb",
            "hours": [
                {
                    "datetime": "12:00:00",
                    "datetimeEpoch": 1741708800,
                    "temp": 60.4,
                    "feelslike": 60.4,
                    "humidity": 25.7,
                    "dew": 25,
                    "precip": 0,
                    "precipprob": 0,
                    "snow": 0,
                    "snowdepth": 0,
                    "preciptype": null,
                    "windgust": 19.7,
                    "windspeed": 7.5,
                    "winddir": 178,
                    "pressure": 1008.8,
                    "visibility": 9.9,
                    "cloudcover": 0,
                    "solarradiation": 708,
                    "solarenergy": 2.5,
                    "uvindex": 7,
                    "severerisk": 10,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": [
                        "KTEB",
                        "KLGA",
                        "F1417",
                        "KNYC"
                    ],
                    "source": "obs"
                },
                {
                    "datetime": "13:00:00",
                    "datetimeEpoch": 1741712400,
                    "temp": 60,
                    "feelslike": 60,
                    "humidity": 36.06,
                    "dew": 33,
                    "precip": 0,
                    "precipprob": 0,
                    "snow": 0,
                    "snowdepth": 0,
                    "preciptype": null,
                    "windgust": 10.3,
                    "windspeed": 8.1,
                    "winddir": 190,
                    "pressure": 1009,
                    "visibility": 10.1,
                    "cloudcover": 6,
                    "solarradiation": 730,
                    "solarenergy": 2.6,
                    "uvindex": 7,
                    "severerisk": 10,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                }
            ]
        }
    ],
    "alerts": [
        {
            "event": "Special Weather Statement",
            "headline": "Special Weather Statement issued March 11 at 8:59AM EDT by NWS Upton NY",
            "ends": "2025-03-11T19:00:00",
            "endsEpoch": 1741734000,
            "onset": "2025-03-11T08:59:00",
            "onsetEpoch": 1741697940,
            "id": "urn:oid:2.49.0.1.840.0.7dee1191f90f2c06900ce9197172ebeec8af63d3.003.1",
            "language": "en",
            "link": "http://www.weather.gov",
            "description": "The combination of low relative humidity values of 20 to 30\npercent and a few wind gusts approaching 20 mph will create an\nelevated risk for fire spread across the region today.\n\nExercise caution handling any potential ignition sources,\nincluding machinery, cigarettes, and matches. Any fires that\nignite will have the potential to spread quickly.\n\nThis forecast considers meteorological, fuel, and land conditions\nand has been developed in coordination with state fire and land\nmanagement officials.\n"
        }
    ],
    "stations": {
        "KLGA": {
            "distance": 9930,
            "latitude": 40.77,
            "longitude": -73.9,
            "useCount": 0,
            "id": "KLGA",
            "name": "KLGA",
            "quality": 100,
            "contribution": 0
        },
        "KTEB": {
            "distance": 7833,
            "latitude": 40.85,
            "longitude": -74.06,
            "useCount": 0,
            "id": "KTEB",
            "name": "KTEB",
            "quality": 100,
            "contribution": 0
        },
        "F1417": {
            "distance": 4928,
            "latitude": 40.745,
            "longitude": -74.029,
            "useCount": 0,
            "id": "F1417",
            "name": "FW1417 Hoboken NJ US",
            "quality": 0,
            "contribution": 0
        },
        "KNYC": {
            "distance": 3606,
            "latitude": 40.77,
            "longitude": -73.98,
            "useCount": 0,
            "id": "KNYC",
            "name": "KNYC",
            "quality": 100,
            "contribution": 0
        }
    },
    "currentConditions": {
        "datetime": "12:05:00",
        "datetimeEpoch": 1741709100,
        "temp": 60.2,
        "feelslike": 60.2,
        "humidity": 27.4,
        "dew": 26.4,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 10.1,
        "windspeed": 6.1,
        "winddir": 181,
        "pressure": 1009,
        "visibility": 9.9,
        "cloudcover": 0,
        "solarradiation": 708,
        "solarenergy": 2.5,
        "uvindex": 7,
        "conditions": "Clear",
        "icon": "clear-day",
        "stations": [
            "KTEB",
            "F1417",
            "KNYC"
        ],
        "source": "obs",
        "sunrise": "07:13:43",
        "sunriseEpoch": 1741691623,
        "sunset": "18:58:54",
        "sunsetEpoch": 1741733934,
        "moonphase": 0.41
    }
}

